# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98196eda9800051dcb2437e10103dda07c3031b90ec53e83f5707a6ea2bfa58d24a9f54fa45cb9280fd9d5d4d73ed5c698d3e027add86c0f31fa37300dfebea1
  secret_forecast: <%= ENV["SECRET_FORECAST"] %>

test:
  secret_key_base: 9f12f5a8fb162f1a6451962e9afff28d0d99706c2a39bcbedf4c5f2c1b539fd3d83d21b0c70f12508cffc48083590aa1d06bb93fb0dfae18c617a8052ccc6ca5
  secret_forecast: <%= ENV["SECRET_FORECAST"] %>
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_forecast: <%= ENV["SECRET_FORECAST"] %>
